version: '3.8'
services:
  porter:
    build:
      context: ./porter
      dockerfile: Dockerfile.porter
      target: test
    ports:
      - 8080:8080
    tty: true
    command: pnpm run watch
    volumes:
      - type: bind
        source: ./porter
        target: /app
      - type: volume
        source: node_modules
        target: /app/node_modules
volumes:
  node_modules:
