# SEE: https://medium.com/@alpercitak/nest-js-use-pnpm-on-docker-81998ab4d8a1

FROM node:18-alpine AS base

RUN corepack enable pnpm
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN pnpm install


FROM base AS dev
EXPOSE 8080
# This would be ignored if you use docker-compose & do bind mount.
COPY . .
CMD ["pnpm", "run", "watch"]

FROM base AS prod
EXPOSE 8080
COPY . .

ENV NODE_ENV=production

RUN pnpm run build

CMD ["pnpm", "run", "start"]
