name: test

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: test
      run: docker compose -f docker-compose.yml run --rm porter pnpm run test

