name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    
    - name: build
      run: docker compose build

    - name: test
      run: docker compose run --rm porter pnpm run test
